export type InventoryStatus =
  | "in_stock"
  | "made_to_order"
  | "low_stock"
  | "sold_out"
  | "coming_soon"
  | "preorder";

export type ProductImage = {
  src: string | null;
  alt: string;
};

export type ProductVariant = {
  id: string;
  label: string;
  color: string;
  style?: string;
  image: ProductImage;
};

export type Product = {
  id: string;
  slug: string;
  name: string;
  shortDescription: string;
  fullDescription: string;
  category: string;
  collection: string;
  price: number | null;
  compareAtPrice: number | null;
  currency: "MXN";
  images: ProductImage[];
  availableColors: string[];
  availableSizes: string[];
  inventoryStatus: InventoryStatus;
  productionType: "ready_to_ship" | "made_to_order";
  productionTime: string;
  materials: string;
  careInstructions: string;
  featured: boolean;
  newProduct: boolean;
  bestseller: boolean;
  relatedProducts: string[];
  catalogStatus?: "active" | "coming_soon" | "hidden";
  variants?: ProductVariant[];
  mediaLayout?: "square" | "wide";
};

export const brand = {
  announcement: "PRÓXIMAMENTE · PRIMERA COLECCIÓN FIERRO",
  name: "FIERRO",
  statement: "Fierro marca tu camino.",
  instagramLabel: "@fierro.shop",
  instagramUrl: "https://instagram.com/fierro.shop",
};

export const navigation = [
  { label: "Tienda", href: "/tienda" },
  { label: "Gorras", href: "/tienda?tipo=gorras" },
  { label: "Playeras", href: "/tienda?tipo=playeras" },
  { label: "Personalizados", href: "/personalizados" },
  { label: "Nuestra historia", href: "/nuestra-historia" },
];

export const collections = [
  {
    id: "flora-del-desierto",
    name: "Flora del Desierto",
    description: "Órgano, sahuaro, mezquite, palo verde y otras plantas nativas observadas desde el paisaje sonorense.",
    short: "Plantas nativas, trazos sobrios.",
    photo: "Flora del desierto",
    tone: "sand",
    count: 6,
  },
  {
    id: "ganado-sonorense",
    name: "Ganado Sonorense",
    description: "Ganado, caballos y vida de rancho tratados con autenticidad, sin caricatura.",
    short: "Orgullo del trabajo ganadero.",
    photo: "Ganado sonorense",
    tone: "leather",
    count: 4,
  },
  {
    id: "rio-sonora",
    name: "Río Sonora",
    description: "Diseños inspirados por Ures, sus comunidades, paisajes y tradiciones.",
    short: "Paisaje, memoria y comunidad.",
    photo: "Camino al Río Sonora",
    tone: "mesquite",
    count: 5,
  },
  {
    id: "para-la-gente-de-trabajo",
    name: "Para la Gente de Trabajo",
    description: "Productos limpios, accesibles y pensados para uso cotidiano. Toda promesa de desempeño se validará antes de publicarse.",
    short: "Lo cotidiano, sin disfraz.",
    photo: "Jornada de rancho",
    tone: "carbon",
    count: 0,
  },
  {
    id: "gorras-fierro",
    name: "Gorras FIERRO",
    description: "Gorras de uso diario con identidad limpia y detalles sobrios.",
    short: "Uso diario, marca limpia.",
    photo: "Gorras FIERRO",
    tone: "dust",
    count: 10,
  },
];

export const products: Product[] = [
  {
    id: "fie-tee-brangus",
    slug: "playera-brangus",
    name: "Playera Brangus",
    shortDescription: "Gráfica posterior de un toro Brangus con símbolo FIERRO al frente.",
    fullDescription: "Una playera gráfica de presencia fuerte: ilustración de toro Brangus y paisaje sonorense en la espalda, acompañada por el símbolo FIERRO al frente. Colores, tallas y precio se muestran para validar el recorrido de compra.",
    category: "playeras",
    collection: "ganado-sonorense",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/playeras/brangus/olivo.webp", alt: "Playera Brangus olivo, vista posterior y frontal" }],
    availableColors: ["Carbón", "Arena", "Olivo"],
    availableSizes: ["CH", "M", "G", "XG"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: true,
    newProduct: true,
    bestseller: false,
    relatedProducts: ["fie-tee-caballo", "fie-tee-gallo", "fie-cap-001"],
    catalogStatus: "active",
    mediaLayout: "wide",
    variants: [
      { id: "olivo", label: "Olivo", color: "Olivo", image: { src: "/media/products/playeras/brangus/olivo.webp", alt: "Playera Brangus olivo, vista posterior y frontal" } },
      { id: "carbon", label: "Carbón", color: "Carbón", image: { src: "/media/products/playeras/brangus/carbon.webp", alt: "Playera Brangus carbón, vista posterior y frontal" } },
      { id: "arena", label: "Arena", color: "Arena", image: { src: "/media/products/playeras/brangus/arena.webp", alt: "Playera Brangus arena, vista posterior y frontal" } },
    ],
  },
  {
    id: "fie-tee-caballo",
    slug: "playera-caballo-del-desierto",
    name: "Playera Caballo del Desierto",
    shortDescription: "Caballo ensillado frente al paisaje del desierto sonorense.",
    fullDescription: "Una escena de caballo y desierto ocupa la espalda, mientras el símbolo FIERRO mantiene el frente limpio. Esta ficha es demostrativa hasta confirmar materiales, corte e inventario.",
    category: "playeras",
    collection: "ganado-sonorense",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/playeras/caballo-desierto/oxido.webp", alt: "Playera Caballo del Desierto óxido rojo, vista posterior y frontal" }],
    availableColors: ["Carbón", "Hueso", "Índigo", "Olivo", "Óxido"],
    availableSizes: ["CH", "M", "G", "XG"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: true,
    newProduct: true,
    bestseller: false,
    relatedProducts: ["fie-tee-brangus", "fie-tee-truck", "fie-cap-005"],
    catalogStatus: "active",
    mediaLayout: "wide",
    variants: [
      { id: "oxido", label: "Óxido", color: "Óxido rojo", image: { src: "/media/products/playeras/caballo-desierto/oxido.webp", alt: "Playera Caballo del Desierto óxido rojo" } },
      { id: "carbon", label: "Carbón", color: "Carbón", image: { src: "/media/products/playeras/caballo-desierto/carbon.webp", alt: "Playera Caballo del Desierto carbón" } },
      { id: "hueso", label: "Hueso", color: "Hueso", image: { src: "/media/products/playeras/caballo-desierto/hueso.webp", alt: "Playera Caballo del Desierto hueso" } },
      { id: "indigo", label: "Índigo", color: "Índigo", image: { src: "/media/products/playeras/caballo-desierto/indigo.webp", alt: "Playera Caballo del Desierto índigo" } },
      { id: "olivo", label: "Olivo", color: "Olivo", image: { src: "/media/products/playeras/caballo-desierto/olivo.webp", alt: "Playera Caballo del Desierto olivo" } },
    ],
  },
  {
    id: "fie-tee-f-herrar",
    slug: "playera-f-de-herrar",
    name: "Playera F de Herrar",
    shortDescription: "La F de FIERRO reinterpretada como herramienta y marca del camino.",
    fullDescription: "Una gráfica frontal de una tinta inspirada en el fierro de herrar y el trabajo cotidiano. Las versiones cambian color de prenda y tratamiento de tinta.",
    category: "playeras",
    collection: "para-la-gente-de-trabajo",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/playeras/f-de-herrar/natural-dos-tintas.webp", alt: "Playera F de Herrar natural dos tintas, vista frontal y posterior" }],
    availableColors: ["Carbón · una tinta", "Gris · una tinta", "Natural · dos tintas"],
    availableSizes: ["CH", "M", "G", "XG"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: true,
    newProduct: true,
    bestseller: false,
    relatedProducts: ["fie-tee-hecho-sonora", "fie-tee-truck", "fie-cap-010"],
    catalogStatus: "active",
    mediaLayout: "wide",
    variants: [
      { id: "natural-dos-tintas", label: "Natural · dos tintas", color: "Natural", style: "Dos tintas", image: { src: "/media/products/playeras/f-de-herrar/natural-dos-tintas.webp", alt: "Playera F de Herrar natural dos tintas" } },
      { id: "carbon-una-tinta", label: "Carbón · una tinta", color: "Carbón", style: "Una tinta", image: { src: "/media/products/playeras/f-de-herrar/carbon-una-tinta.webp", alt: "Playera F de Herrar carbón una tinta" } },
      { id: "gris-una-tinta", label: "Gris · una tinta", color: "Gris", style: "Una tinta", image: { src: "/media/products/playeras/f-de-herrar/gris-una-tinta.webp", alt: "Playera F de Herrar gris una tinta" } },
    ],
  },
  {
    id: "fie-tee-gallo",
    slug: "playera-gallo-de-rancho",
    name: "Playera Gallo de Rancho",
    shortDescription: "Ilustración posterior de gallo con símbolo FIERRO al frente.",
    fullDescription: "Una pieza gráfica inspirada en la presencia y color del gallo de rancho. La espalda lleva la ilustración principal y el frente conserva el símbolo FIERRO.",
    category: "playeras", collection: "ganado-sonorense", price: 599, compareAtPrice: null, currency: "MXN",
    images: [{ src: "/media/products/playeras/gallo-de-rancho/arena.webp", alt: "Playera Gallo de Rancho arena, vista posterior y frontal" }],
    availableColors: ["Carbón", "Arena", "Olivo"], availableSizes: ["CH", "M", "G", "XG"], inventoryStatus: "in_stock", productionType: "ready_to_ship",
    productionTime: "[por confirmar]", materials: "[materiales y composición por confirmar]", careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false, newProduct: true, bestseller: false, relatedProducts: ["fie-tee-brangus", "fie-tee-caballo", "fie-cap-006"], catalogStatus: "active", mediaLayout: "wide",
    variants: [
      { id: "arena", label: "Arena", color: "Arena", image: { src: "/media/products/playeras/gallo-de-rancho/arena.webp", alt: "Playera Gallo de Rancho arena" } },
      { id: "carbon", label: "Carbón", color: "Carbón", image: { src: "/media/products/playeras/gallo-de-rancho/carbon.webp", alt: "Playera Gallo de Rancho carbón" } },
      { id: "olivo", label: "Olivo", color: "Olivo", image: { src: "/media/products/playeras/gallo-de-rancho/olivo.webp", alt: "Playera Gallo de Rancho olivo" } },
    ],
  },
  {
    id: "fie-tee-hecho-sonora",
    slug: "playera-hecho-en-sonora",
    name: "Playera Hecho en Sonora",
    shortDescription: "Mapa de Sonora y una declaración directa de origen.",
    fullDescription: "Una gráfica frontal limpia con el contorno de Sonora, estrella y tipografía de inspiración western. Esta versión de prueba permite comparar tres combinaciones de color.",
    category: "playeras", collection: "rio-sonora", price: 599, compareAtPrice: null, currency: "MXN",
    images: [{ src: "/media/products/playeras/hecho-en-sonora/carbon-oro.webp", alt: "Playera Hecho en Sonora carbón y oro" }],
    availableColors: ["Carbón/Oro", "Natural/Negro", "Óxido/Hueso"], availableSizes: ["CH", "M", "G", "XG"], inventoryStatus: "in_stock", productionType: "ready_to_ship",
    productionTime: "[por confirmar]", materials: "[materiales y composición por confirmar]", careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false, newProduct: true, bestseller: false, relatedProducts: ["fie-tee-f-herrar", "fie-tee-truck", "fie-cap-009"], catalogStatus: "active", mediaLayout: "wide",
    variants: [
      { id: "carbon-oro", label: "Carbón/Oro", color: "Carbón", image: { src: "/media/products/playeras/hecho-en-sonora/carbon-oro.webp", alt: "Playera Hecho en Sonora carbón y oro" } },
      { id: "natural-negro", label: "Natural/Negro", color: "Natural", image: { src: "/media/products/playeras/hecho-en-sonora/natural-negro.webp", alt: "Playera Hecho en Sonora natural y negro" } },
      { id: "oxido-hueso", label: "Óxido/Hueso", color: "Óxido", image: { src: "/media/products/playeras/hecho-en-sonora/oxido-hueso.webp", alt: "Playera Hecho en Sonora óxido y hueso" } },
    ],
  },
  {
    id: "fie-tee-truck",
    slug: "playera-truck-del-desierto",
    name: "Playera Truck del Desierto",
    shortDescription: "Pickup de trabajo frente al paisaje del desierto.",
    fullDescription: "Una pickup y el paisaje sonorense protagonizan la espalda, con símbolo FIERRO al frente. Las variantes exploran color, corte y acabado de la prenda.",
    category: "playeras", collection: "para-la-gente-de-trabajo", price: 599, compareAtPrice: null, currency: "MXN",
    images: [{ src: "/media/products/playeras/truck-del-desierto/indigo-workwear.webp", alt: "Playera Truck del Desierto índigo corte workwear" }],
    availableColors: ["Carbón Boxy", "Hueso Relajada", "Índigo Workwear", "Ringer Hueso/Café"], availableSizes: ["CH", "M", "G", "XG"], inventoryStatus: "in_stock", productionType: "ready_to_ship",
    productionTime: "[por confirmar]", materials: "[materiales y composición por confirmar]", careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false, newProduct: true, bestseller: false, relatedProducts: ["fie-tee-caballo", "fie-tee-f-herrar", "fie-cap-007"], catalogStatus: "active", mediaLayout: "wide",
    variants: [
      { id: "indigo-workwear", label: "Índigo Workwear", color: "Índigo", style: "Workwear", image: { src: "/media/products/playeras/truck-del-desierto/indigo-workwear.webp", alt: "Playera Truck del Desierto índigo workwear" } },
      { id: "carbon-boxy", label: "Carbón Boxy", color: "Carbón", style: "Boxy", image: { src: "/media/products/playeras/truck-del-desierto/carbon-boxy.webp", alt: "Playera Truck del Desierto carbón boxy" } },
      { id: "hueso-relajada", label: "Hueso Relajada", color: "Hueso", style: "Relajada", image: { src: "/media/products/playeras/truck-del-desierto/hueso-relajada.webp", alt: "Playera Truck del Desierto hueso relajada" } },
      { id: "ringer-hueso-cafe", label: "Ringer Hueso/Café", color: "Hueso/Café", style: "Ringer", image: { src: "/media/products/playeras/truck-del-desierto/ringer-hueso-cafe.webp", alt: "Playera Truck del Desierto ringer hueso y café" } },
    ],
  },
  {
    id: "fie-cap-001",
    slug: "gorra-bronco",
    name: "Gorra Bronco",
    shortDescription: "Arena y café con el símbolo de toro FIERRO al frente.",
    fullDescription: "Una combinación sobria en arena y café, rematada por el símbolo de toro FIERRO bordado al frente. Su contraste y paneles de malla le dan una presencia ranchera limpia para el uso diario.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-bronco.png", alt: "Gorra Bronco arena y café con símbolo de toro FIERRO" }],
    availableColors: ["Arena y café"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: true,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-002", "fie-cap-004", "fie-cap-005"],
  },
  {
    id: "fie-cap-002",
    slug: "gorra-oliva-ranch",
    name: "Gorra Oliva Ranch",
    shortDescription: "Olivo y beige con sello circular FIERRO.",
    fullDescription: "Una gorra en tonos olivo y beige con un sello circular de acabado café al frente. El contraste entre paneles sólidos y malla crea una pieza discreta con identidad de rancho.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-oliva-ranch.png", alt: "Gorra Oliva Ranch olivo y beige con sello circular FIERRO" }],
    availableColors: ["Olivo y beige"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-004", "fie-cap-006", "fie-cap-008"],
  },
  {
    id: "fie-cap-003",
    slug: "gorra-western-script",
    name: "Gorra Western Script",
    shortDescription: "Café con el nombre Fierro bordado en estilo western.",
    fullDescription: "Un modelo café de apariencia clásica, protagonizado por el bordado Fierro en tipografía western. El detalle claro sobre el fondo oscuro aporta contraste sin perder el carácter sobrio de la colección.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-western-script.png", alt: "Gorra Western Script café con bordado Fierro" }],
    availableColors: ["Café"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-001", "fie-cap-005", "fie-cap-010"],
  },
  {
    id: "fie-cap-004",
    slug: "gorra-sello-circular",
    name: "Gorra Sello Circular",
    shortDescription: "Arena y café con parche circular FIERRO.",
    fullDescription: "Una interpretación limpia de la paleta arena y café, con el sello circular FIERRO como punto central. La malla posterior y la visera contrastante completan su estética de campo.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-sello-circular.png", alt: "Gorra Sello Circular arena y café con parche FIERRO" }],
    availableColors: ["Arena y café"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-001", "fie-cap-002", "fie-cap-009"],
  },
  {
    id: "fie-cap-005",
    slug: "gorra-edicion-desierto",
    name: "Gorra Edición Desierto",
    shortDescription: "Tono desierto con símbolo de toro bordado al tono.",
    fullDescription: "Una gorra monocromática en café desierto que lleva el símbolo de toro bordado al tono. El resultado es una pieza cálida y discreta, inspirada en los colores secos del paisaje sonorense.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-edicion-desierto.png", alt: "Gorra Edición Desierto café con símbolo de toro tonal" }],
    availableColors: ["Café desierto"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-001", "fie-cap-003", "fie-cap-010"],
  },
  {
    id: "fie-cap-006",
    slug: "gorra-mezquite",
    name: "Gorra Mezquite",
    shortDescription: "Olivo y café con un mezquite bordado al frente.",
    fullDescription: "Los tonos olivo, café y beige enmarcan un mezquite bordado al frente. Es una pieza que lleva una silueta reconocible del paisaje del norte con un tratamiento directo y sobrio.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-mezquite.png", alt: "Gorra Mezquite olivo, café y beige con árbol bordado" }],
    availableColors: ["Olivo, café y beige"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-002", "fie-cap-007", "fie-cap-008"],
  },
  {
    id: "fie-cap-007",
    slug: "gorra-tractor-del-campo",
    name: "Gorra Tractor del Campo",
    shortDescription: "Olivo y azul con parche de tractor.",
    fullDescription: "Un diseño en olivo, azul y beige con un parche de tractor al frente. La combinación de colores mantiene el motivo agrícola como protagonista sin recargar la pieza.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-tractor-del-campo.png", alt: "Gorra Tractor del Campo olivo, azul y beige con parche de tractor" }],
    availableColors: ["Olivo, azul y beige"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-006", "fie-cap-008", "fie-cap-010"],
  },
  {
    id: "fie-cap-008",
    slug: "gorra-herradura-del-norte",
    name: "Gorra Herradura del Norte",
    shortDescription: "Olivo y café con herradura bordada.",
    fullDescription: "Una gorra en olivo, café y beige con herradura bordada al frente. Su símbolo sencillo y su paleta terrosa mantienen una presencia western contenida.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-herradura-del-norte.png", alt: "Gorra Herradura del Norte olivo y café con herradura bordada" }],
    availableColors: ["Olivo, café y beige"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-002", "fie-cap-006", "fie-cap-009"],
  },
  {
    id: "fie-cap-009",
    slug: "gorra-potro-libre",
    name: "Gorra Potro Libre",
    shortDescription: "Arena y café con caballo bordado al frente.",
    fullDescription: "Un caballo en movimiento bordado sobre paneles arena, acompañado por visera y malla en café. El motivo ecuestre concentra la atención y conserva una lectura clara en la silueta de la gorra.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-potro-libre.png", alt: "Gorra Potro Libre arena y café con caballo bordado" }],
    availableColors: ["Arena y café"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-004", "fie-cap-008", "fie-cap-010"],
  },
  {
    id: "fie-cap-010",
    slug: "gorra-alambre-de-puas",
    name: "Gorra Alambre de Púas",
    shortDescription: "Negra con alambre de púas bordado al frente.",
    fullDescription: "Una gorra negra de contraste contenido con una línea de alambre de púas bordada al frente. El diseño mantiene una gráfica directa vinculada al campo y los límites del terreno.",
    category: "gorras",
    collection: "gorras-fierro",
    price: 599,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: "/media/products/gorras/gorra-alambre-de-puas.png", alt: "Gorra Alambre de Púas negra con bordado frontal" }],
    availableColors: ["Negro"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[materiales y composición por confirmar]",
    careInstructions: "[instrucciones de cuidado por confirmar]",
    featured: false,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-003", "fie-cap-005", "fie-cap-009"],
  },
  {
    id: "fie-patch-001",
    slug: "parche-fierro",
    name: "Parche FIERRO",
    shortDescription: "Parche con el símbolo FIERRO.",
    fullDescription: "[Descripción completa por validar.]",
    category: "accesorios",
    collection: "rio-sonora",
    price: null,
    compareAtPrice: null,
    currency: "MXN",
    images: [],
    availableColors: ["Arena"],
    availableSizes: ["Unitalla"],
    inventoryStatus: "in_stock",
    productionType: "ready_to_ship",
    productionTime: "[por confirmar]",
    materials: "[por confirmar]",
    careInstructions: "[por confirmar]",
    featured: true,
    newProduct: false,
    bestseller: false,
    relatedProducts: ["fie-cap-001"],
  },
  {
    id: "fie-hood-001",
    slug: "hoodie-del-monte-somos",
    name: "Hoodie Del Monte Somos",
    shortDescription: "Hoodie de muestra de la colección Ganado Sonorense.",
    fullDescription: "[Descripción completa por validar.]",
    category: "hoodies",
    collection: "ganado-sonorense",
    price: null,
    compareAtPrice: null,
    currency: "MXN",
    images: [{ src: null, alt: "Fotografía lifestyle de Hoodie Del Monte Somos" }],
    availableColors: ["Olivo", "Carbón"],
    availableSizes: ["CH", "M", "G", "XG"],
    inventoryStatus: "coming_soon",
    productionType: "made_to_order",
    productionTime: "[por confirmar]",
    materials: "[por confirmar]",
    careInstructions: "[por confirmar]",
    featured: true,
    newProduct: true,
    bestseller: false,
    relatedProducts: ["fie-tee-truck"],
  },
];

export const faqs = [
  ["¿Puedo comprar en este sitio?", "Todavía no. El carrito y el checkout son una demostración y no generan cobros, pedidos ni reservan inventario."],
  ["¿A dónde hacen envíos?", "La cobertura, las paqueterías, los costos y los plazos se publicarán antes de habilitar ventas reales."],
  ["¿Cuánto tarda en prepararse un pedido?", "Los tiempos se definirán por producto antes del lanzamiento comercial."],
  ["¿Cómo elijo mi talla?", "Las tablas y medidas se publicarán junto con cada prenda antes de que pueda comprarse."],
  ["¿Puedo hacer cambios o devoluciones?", "La política definitiva se publicará antes de aceptar pedidos. El checkout actual no crea compras sujetas a cambios o devoluciones."],
  ["¿Las playeras ya se pueden comprar?", "Puedes explorar sus mockups, variantes y tallas dentro del flujo de prueba, pero todavía no se aceptan pagos, apartados ni pedidos reales."],
  ["¿Cómo cuido mi producto?", "Cada ficha incluirá instrucciones de cuidado verificadas antes del lanzamiento comercial."],
  ["¿Venden por mayoreo?", "Sí. En personalizados puedes escribir cualquier cantidad entre 1 y 5,000 piezas. Los niveles sirven como atajos para lotes frecuentes; FIERRO confirma el precio después de revisar técnica, material y archivo."],
  ["¿Qué métodos de pago aceptan?", "Todavía no hay una pasarela conectada. Ningún formulario del sitio solicita datos de tarjeta."],
];

export function confirmedCopy(value: string, fallback: string) {
  return value.includes("[por confirmar]") || value.startsWith("[") ? fallback : value;
}

export function getCatalogStatus(product: Product): "active" | "coming_soon" | "hidden" {
  if (product.catalogStatus) return product.catalogStatus;
  return product.category === "gorras" && product.price !== null ? "active" : "hidden";
}

export function getProductVariants(product: Product): ProductVariant[] {
  if (product.variants?.length) return product.variants;
  return product.availableColors.map((color, index) => ({
    id: `option-${index + 1}`,
    label: color,
    color,
    image: product.images[0] ?? { src: null, alt: product.name },
  }));
}

export const activeProducts = products.filter((product) => getCatalogStatus(product) === "active");

export const statusLabels: Record<InventoryStatus, string> = {
  in_stock: "Disponible en la demostración",
  made_to_order: "Sobre pedido",
  low_stock: "Disponibilidad limitada",
  sold_out: "Agotado",
  coming_soon: "Próximamente",
  preorder: "Preventa",
};
